In [ ]:
import tensorflow_datasets as tfds

RAW_DATASET_NAMES = [
    "libero_10_no_noops",
    "libero_goal_no_noops",
    "libero_object_no_noops",
    "libero_spatial_no_noops",
]  # For simplicity we will combine multiple Libero datasets into one training dataset

data_dir = '/home/wl5915/code/vla/datasets/modified_libero_rlds'
for raw_dataset_name in RAW_DATASET_NAMES:
    raw_dataset = tfds.load(raw_dataset_name, data_dir=data_dir, split="train")
    for episode in raw_dataset:
        display(episode)
        display(episode["episode_metadata"])
        for step in episode["steps"].as_numpy_iterator():
            display(step)
            break
        break

2025-02-18 22:25:30.271765: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739935530.319851  321964 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739935530.329626  321964 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-18 22:25:30.418183: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1739935537.808316  321964 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21

{'episode_metadata': {'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_10/LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate_demo.hdf5'>},
 'steps': <_VariantDataset element_spec={'action': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'discount': TensorSpec(shape=(), dtype=tf.float32, name=None), 'is_first': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_last': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_terminal': TensorSpec(shape=(), dtype=tf.bool, name=None), 'language_instruction': TensorSpec(shape=(), dtype=tf.string, name=None), 'observation': {'image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None), 'joint_state': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'state': TensorSpec(shape=(8,), dtype=tf.float32, name=None), 'wrist_image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None)}, '

{'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_10/LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate_and_put_the_yellow_and_white_mug_on_the_right_plate_demo.hdf5'>}

{'action': array([ 0.01607143,  0.        , -0.        ,  0.        ,  0.        ,
        -0.        , -1.        ], dtype=float32),
 'discount': np.float32(1.0),
 'is_first': np.True_,
 'is_last': np.False_,
 'is_terminal': np.False_,
 'language_instruction': b'put the white mug on the left plate and put the yellow and white mug on the right plate',
 'observation': {'image': array([[[ 13,  13,  13],
          [ 13,  13,  13],
          [ 13,  13,  13],
          ...,
          [116, 117, 112],
          [115, 116, 111],
          [114, 115, 110]],
  
         [[ 13,  13,  13],
          [ 13,  13,  13],
          [ 13,  13,  13],
          ...,
          [116, 117, 112],
          [115, 116, 111],
          [114, 115, 110]],
  
         [[ 13,  13,  13],
          [ 13,  13,  13],
          [ 13,  13,  13],
          ...,
          [116, 117, 112],
          [115, 116, 111],
          [114, 115, 110]],
  
         ...,
  
         [[ 83,  64,  50],
          [ 82,  63,  49],
        

{'episode_metadata': {'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_goal/put_the_bowl_on_the_plate_demo.hdf5'>},
 'steps': <_VariantDataset element_spec={'action': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'discount': TensorSpec(shape=(), dtype=tf.float32, name=None), 'is_first': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_last': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_terminal': TensorSpec(shape=(), dtype=tf.bool, name=None), 'language_instruction': TensorSpec(shape=(), dtype=tf.string, name=None), 'observation': {'image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None), 'joint_state': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'state': TensorSpec(shape=(8,), dtype=tf.float32, name=None), 'wrist_image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None)}, 'reward': TensorSpec(shape=(), dtype=tf.float32, name=None)}>}

{'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_goal/put_the_bowl_on_the_plate_demo.hdf5'>}

{'action': array([ 0.07232143,  0.        , -0.        , -0.01178571,  0.04392857,
         0.03535714, -1.        ], dtype=float32),
 'discount': np.float32(1.0),
 'is_first': np.True_,
 'is_last': np.False_,
 'is_terminal': np.False_,
 'language_instruction': b'put the bowl on the plate',
 'observation': {'image': array([[[108, 107, 103],
          [108, 107, 103],
          [109, 108, 104],
          ...,
          [107, 106, 102],
          [107, 106, 102],
          [107, 106, 102]],
  
         [[108, 107, 103],
          [108, 107, 103],
          [109, 108, 104],
          ...,
          [108, 107, 103],
          [108, 107, 103],
          [107, 106, 102]],
  
         [[108, 107, 103],
          [108, 107, 103],
          [109, 108, 104],
          ...,
          [108, 107, 103],
          [108, 107, 103],
          [107, 106, 102]],
  
         ...,
  
         [[200, 183, 167],
          [195, 178, 162],
          [194, 177, 161],
          ...,
          [179, 164, 145],
 

{'episode_metadata': {'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_object/pick_up_the_orange_juice_and_place_it_in_the_basket_demo.hdf5'>},
 'steps': <_VariantDataset element_spec={'action': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'discount': TensorSpec(shape=(), dtype=tf.float32, name=None), 'is_first': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_last': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_terminal': TensorSpec(shape=(), dtype=tf.bool, name=None), 'language_instruction': TensorSpec(shape=(), dtype=tf.string, name=None), 'observation': {'image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None), 'joint_state': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'state': TensorSpec(shape=(8,), dtype=tf.float32, name=None), 'wrist_image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None)}, 'reward': TensorSpec(shape=(), dtype=tf.float32, nam

{'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_object/pick_up_the_orange_juice_and_place_it_in_the_basket_demo.hdf5'>}

{'action': array([-0.14196429,  0.02410714, -0.06160714, -0.01607143, -0.02035714,
        -0.03642857, -1.        ], dtype=float32),
 'discount': np.float32(1.0),
 'is_first': np.True_,
 'is_last': np.False_,
 'is_terminal': np.False_,
 'language_instruction': b'pick up the orange juice and place it in the basket',
 'observation': {'image': array([[[134, 135, 129],
          [133, 134, 128],
          [133, 134, 128],
          ...,
          [135, 134, 129],
          [135, 134, 129],
          [135, 134, 129]],
  
         [[133, 134, 128],
          [132, 133, 127],
          [132, 133, 127],
          ...,
          [134, 133, 128],
          [134, 133, 128],
          [134, 133, 128]],
  
         [[133, 134, 128],
          [132, 133, 127],
          [132, 133, 127],
          ...,
          [133, 132, 127],
          [133, 132, 127],
          [133, 132, 127]],
  
         ...,
  
         [[197, 190, 180],
          [196, 189, 179],
          [199, 192, 182],
          ...,
  

{'episode_metadata': {'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_spatial/pick_up_the_black_bowl_next_to_the_cookie_box_and_place_it_on_the_plate_demo.hdf5'>},
 'steps': <_VariantDataset element_spec={'action': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'discount': TensorSpec(shape=(), dtype=tf.float32, name=None), 'is_first': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_last': TensorSpec(shape=(), dtype=tf.bool, name=None), 'is_terminal': TensorSpec(shape=(), dtype=tf.bool, name=None), 'language_instruction': TensorSpec(shape=(), dtype=tf.string, name=None), 'observation': {'image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None), 'joint_state': TensorSpec(shape=(7,), dtype=tf.float32, name=None), 'state': TensorSpec(shape=(8,), dtype=tf.float32, name=None), 'wrist_image': TensorSpec(shape=(256, 256, 3), dtype=tf.uint8, name=None)}, 'reward': TensorSpec(shape=(), 

{'file_path': <tf.Tensor: shape=(), dtype=string, numpy=b'/iris/u/moojink/prismatic-dev/LIBERO/libero/datasets/regenerated--no_noops/libero_spatial/pick_up_the_black_bowl_next_to_the_cookie_box_and_place_it_on_the_plate_demo.hdf5'>}

{'action': array([ 0.13125   , -0.04017857, -0.        ,  0.        , -0.04928571,
        -0.        , -1.        ], dtype=float32),
 'discount': np.float32(1.0),
 'is_first': np.True_,
 'is_last': np.False_,
 'is_terminal': np.False_,
 'language_instruction': b'pick up the black bowl next to the cookie box and place it on the plate',
 'observation': {'image': array([[[108, 107, 103],
          [108, 107, 103],
          [109, 108, 104],
          ...,
          [107, 106, 102],
          [107, 106, 102],
          [107, 106, 102]],
  
         [[108, 107, 103],
          [108, 107, 103],
          [109, 108, 104],
          ...,
          [108, 107, 103],
          [108, 107, 103],
          [107, 106, 102]],
  
         [[108, 107, 103],
          [108, 107, 103],
          [109, 108, 104],
          ...,
          [108, 107, 103],
          [108, 107, 103],
          [107, 106, 102]],
  
         ...,
  
         [[200, 183, 167],
          [195, 178, 162],
          [194, 177, 161

: 